name: teleprompter_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment: 
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies: 
  serverpod_auth_email_flutter: 2.0.1
  serverpod_auth_shared_flutter: 2.0.1
  serverpod_chat_flutter: 2.0.1
  serverpod_flutter: 2.0.1
  cupertino_icons: ^1.0.5
  get: 4.6.6
  flutter: 
    sdk: flutter
  teleprompter_client: 
    path: ../teleprompter_client

dev_dependencies: 
  flutter_lints: '>=3.0.0 <5.0.0'
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

